<h1><?php //echo __('Model Saved With Entity ID %1',$block->getTestModel()->getData('test_id')); ?></h1>
<div class="form">
	<form class="form" data-mage-init='{"validation": {}}' id="custom-form" method="post" autocomplete="off">
   <fieldset class="fieldset">
       <legend class="legend"><span><?php echo __('Personal Information') ?></span></legend><br>
        <div class="field required">
        	<label for="user_name" class="label"><span><?php echo __('Name') ?></span></label>
        	 <div class="control">
               <input type="text" name="name" id="name" value="" title="<?php echo('Name')?>" class="input-text" data-validate="{required:true}">
            </div>
            <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
            <label for="message" class="label"><span><?php echo __('Message') ?></span></label>
            <div class="control">
            	<textarea rows="4" cols="5"id="message" name="message" title="<?php echo __('Message') ?>" class="message-text" data-validate="{required:true}">
            	</textarea>
            </div>
        </div>
   </fieldset>
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
        </div>
    </div>
</form>
</div>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 
   var dataForm = $('#custom-form');
   dataForm.mage('validation', {});
 
});
</script>
