<h1><?php echo __('Model Saved With Entity ID %1',$block->getTestModel()->getData('test_id')); 

	
?></h1>
<?php 
// print_r($block->getTestModel()->getData());?>
<div class="form">
	<form action="filename" method="post">
		<span><h1>Personal Detail</h1></span>
		Email <input type="email" name="email" required=""><br/>
		Password <input type="password" name="psw" required=""><br><br>
		<input type="submit" name="submit">
		<input type="reset" name="reset">
		<a href="#">Forget Password</a>
	</form>

</div>